---
    apiVersion: v1
    kind: Service
    metadata:
      name: chinaappstore-exporter
      labels:
        app: chinaappstore-exporter
    spec:
      ports:
      - port: 8081
        targetPort: 8081
      selector:
        app: chinaappstore-exporter
      sessionAffinity: None
      type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chinaappstore-exporter
  namespace: monitor
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: chinaappstore-exporter
    spec:
      containers:
      - name: chinaappstore-exporter
        image: siangyeh8818/golang.exporter.china.appstore:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          protocol: TCP
        env:
        - name: APPLE_ACCOUNT
          value: "YOUR ACCOUNT"
        - name: APPLE_PASSWORD
          value: "YOUR PASSWORD"
        - name: CRAWLER_INTERNAL_TIME
          value: "300s"
